language: scala
scala:
 - 2.10.4

jdk:
 - openjdk7

branches:
only:
 - master

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libnuma-dev numactl
 - numactl -s

script: ./bin/sbt -Dloglevel=debug test

