language: scala
scala:
 - 2.10.4

jdk:
 - openjdk6
 - openjdk7
 - oraclejdk7
 - oraclejdk8

branches:
only:
 - master

install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libnuma-dev numactl
 - find /usr/lib -type f | grep libnuma.so
 - numactl -show

script: ./bin/sbt -Dloglevel=debug test

